### ISSUE TITLE
Upon app JS Logout(Signout command) does not display Azure AD B2C login page

### ISSUE THREAD

**Issue by vsdotnetguy** [damienbod/Blazor.BFF.AzureB2C.Template#17]
Hi Damien,

VSDotNetGuy again.  We see in your template, you're using a form post based logout to the server side api.  However, we're using a menu drawer based Logout link that when clicked raises an event.  From the event code we post to the server at \api\account\logout using HttpClient.

The server side Logout method is being called and the Signout command seems to run okay.  However, we expected the app would no longer be authenticated so would display the Azure AD B2C login page upon redirect or refresh.

Does your template prompt for AD login after Signout?  If not, any ideas on how to be prompted by Azure AD B2C to login after the server side Signout is completed?

Thx in advance and take care,
Bob Baldwin (aka VSDotNetGuy)

**Comment by damienbod** [comment]
Hi @vsdotnetguy Yes this is exactly the problem I have, the Azure B2C logout only works if I do a form request. The ajax call does not logout on the IDP server. I was not able to find a solution to logout with a Javascript request. 

Greetings Damien

**Comment by vsdotnetguy** [comment]
Thanks for the quick response @damienbod.

Wow, both ways call into the server side Logout API method which issues the SignOut command.  However, it only works if done as a form post from the UI.  That is really strange.  I'm going to test it is working as you say and get back to you if I found a workaround.  Thanks...Bob Baldwin (aka VSDotNetGuy).
