### ISSUE TITLE
DirectController

### ISSUE THREAD

**Issue by vsdotnetguy** [damienbod/Blazor.BFF.AzureB2C.Template#2]
Hi Damien,

I've been looking at the AD B2C BFF Blazor template, it looks good, thx for great work.

I did wonder since include global anti forgery setting in Startup, why did you put [ValidateAntiForgeryToken] on DirectApiController or is this just a left over?

Thx...Bob Baldwin
aka VSDotNetGuy!

**Comment by damienbod** [comment]
Hi Bob

No I did this extra because I have not forced this globally. All API calls need this as a fallback for same site. Of course maybe this could be improved :)

Greetings Damien
