### ISSUE TITLE
Correlation failed error when deployed to container apps and app service containers - missing cookies, maybe samesite issue?

### ISSUE THREAD

**Issue by rogerdawson** [damienbod/Blazor.BFF.AzureB2C.Template#26]
Hello @damienbod , 

I watched your recent stand-up with Jon Galloway which was super interesting and I thought I'd give this BFF template a go. Locally it works great, and deployed to a standard app service plan it works fine too. However, I'm pulling my hair out trying to get it to work with Azure container apps and was hoping you could point me in the right direction to fix this. Please note, before the index page would work I had to I fix another issue with the anti-forgery cookie which was resolved with the following change: 

`options.Cookie.SecurePolicy = CookieSecurePolicy.Always;`

to

`options.Cookie.SecurePolicy = CookieSecurePolicy.SameAsRequest;`

Once the above was resolved the index page shows fine but I unfortunately get the correlation failed error reported below when selecting the login link. Any help with this is greatly appreciated:

**Issue**

Correlation failed error reported when selecting the log-in link on the main page. The container app logs show the following (newest first):

[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[15]

'.AspNetCore.Correlation.JV4ZtwsqyoQzUm0XjKPsZl5UeG7IAsHK18V9J3fEtwU' cookie not found.

[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.Http.ResponseCookies[1]

The cookie '.AspNetCore.Correlation.JV4ZtwsqyoQzUm0XjKPsZl5UeG7IAsHK18V9J3fEtwU' has set 'SameSite=None' and must also set 'Secure'.

[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.Http.ResponseCookies[1]

The cookie '.AspNetCore.OpenIdConnect.Nonce.CfDJ8P3OW6sbpfpEkZYp1w0JsW8f2E0rMU4me_SA7Co14Nm2S8UlmZSemDj0yeKD7P5em5sNOV_0CUKPl2JSHAmZWAqJ1GU_Ni9PMQJSPoMEaGjWmJvwp-0SRuAfja8V4tnB1FFiUapJtdRH_KCWCjo_IXrGJlpg6_7b-zkZ8xl0_GxwOSIk-gOT8150GvMagOBwG8_3W5V3M-GwnpfdQt96kA8WzYNqBVgUUdbe8N821B9ac4_NqG37gna1ubwXtF1MmlQ63XVYkMREGaGWAKY87F0' has set 'SameSite=None' and must also set 'Secure'.

**To Reproduce**

Enable container orchestration and deploy the BFF server to a container registry. 

Create a container app (and supporting resources such as environment, app insights etc.). and deploy the image above.

On the main index page select the 'Log in' link and you will be redirected to the /MicrosoftIdentity/Account/Error page which states 'Correlation failed.'

**Additional notes**
  
Deploying to a standard app service plan works fine. 

Deploying to a container based app service plan does not work either, also producing a 'correlation failed' error. This is probably the quickest path to reproducing the issue as it only takes a few minutes to create the app service.

Many Thanks,

Roger

**Comment by damienbod** [comment]
Hi @rogerdawson Thanks for reporting this. Do you use some sort of gateway, certificate termination? 

Maybe to test, you could use the default cookie settings and see what is required in your system. All cookie configuration is in the server program file. Maybe you could compare to a .NET app which works in your env?

Would love your feedback, would be really great to make this robust for all systems or at least add docs for such deployments.

Greetings Damien

**Comment by rogerdawson** [comment]
Hi @damienbod , 

as I understand it the HTTPS requests coming into Azure container apps (and app service containers) are converted into HTTP requests and this is why the anti-forgery error occurred on the index page and I had to set options.Cookie.SecurePolicy to  'SameAsRequest' rather than 'Always'. Unfortunately, taking a similar approach for the other cookies didn't work for the B2C connection as it meant the login request was made as HTTP which is obviously not allowed. I've got a feeling there's something minor I'm missing here rather than a major problem.

I'll try what you said with a standard .net core web app, no Blazor, and see if I can reproduce the error in the app service containers.

Many Thanks,

Roger

**Comment by rogerdawson** [comment]
Hello @damienbod ,

my vanilla web app also didn't work in the container app service either so after a bit of digging I managed to fix the issue. This article explains it [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1#nginx-configuration) but it basically requires two sections of code adding:

`services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedHost | ForwardedHeaders.XForwardedProto;
});`

and then 

`app.UseForwardedHeaders();`

It appears the last snippet above need to go before app.UseHsts so I simply placed it above the env.IsDevelopment call that sets up the error handling. Annoyingly, I saw this a couple of days ago but from somewhere else initially but 'XForwardedHost' was actually 'XForwardedFor' which doesn't work (I didn't notice this). I changed it to XForwardedHost and it sprang into life.

Thanks for all the good work with these samples, it really helps people like me out,

Roger

**Comment by damienbod** [comment]
Thanks a million for this research. Would you be interested in adding this information to the readme with a PR?

https://github.com/damienbod/Blazor.BFF.AzureB2C.Template/blob/main/README-NUGET.md

If not, I will do it. 

Thanks either way and for the great feedback.

Greetings Damien

**Comment by rogerdawson** [comment]
Hi @damienbod , 

of course, I'll get it done in the next day or two,

Roger

**Comment by damienbod** [comment]
release 1.2.1
